### ISSUE TITLE
Few Design Works!

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#1]
**It's mostly design work.** 

- Create a **favicon** for **VinHack** logo & push it in parent folder. It should be preferably 32px*32px. 

-  Design an image (to be used for FB Open Graph) of **1200 x 630** pixels.

@pvsmounish

**Comment by vinitshahdeo** [comment]
@pvsmounish @ArpitKotecha 

`Push` the **OG image** that you guys have designed.

**Comment by vinitshahdeo** [comment]
@ArpitKotecha 

**Please update the OG image.** 

Ask @pvsmounish, he'll provide you the files. This has been pending since long.

**Comment by ArpitKotecha** [comment]
> @ArpitKotecha
> 
> **Please update the OG image.**
> 
> Ask @pvsmounish, he'll provide you the files. This has been pending since long.

Okay. I'll ask.
