### ISSUE TITLE
VinHack Execution Tasks

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#10]
### Check [this](https://github.com/vinnovateit/VinHack/projects/1) and keep me posted !

Assign these tasks to the members and discuss these in meeting.

@ShreyaAnand

**Comment by ArpitKotecha** [comment]
@vinitshahdeo Vinhack is over. Therefore this issue can be closed.

**Comment by vinitshahdeo** [comment]
**Yupp!**
Forgot to do this!
