### ISSUE TITLE
Few CSS changes!

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#14]
### @ShreyaAnand, What about changing the font?

Can't we have two fonts? Using a single type of font throughout the webpage may seem uninteresting. Ideally, we should have separate font(**some bold types**) for all the headings `<h1>...</h1>` and any classic fonts(say _**Montserrat**_, _**Lato**_) for all the `<p>..</p>` tags.

#### Few font suggestions from my side :

1. [Montserrat](https://fonts.google.com/?selection.family=Montserrat) for paragraph.
2. [Cabin](https://fonts.google.com/?selection.family=Cabin) for paragraph
3. [Oswald](https://fonts.google.com/?selection.family=Oswald) for headings.

> Browse [google fonts](https://fonts.google.com/) to find more interesting fonts.

**Comment by ArpitKotecha** [comment]
@vinitshahdeo Please close this issue as it has been resolved in  PR #17 .

**Comment by vinitshahdeo** [comment]
> @vinitshahdeo Please close this issue as it has been resolved in PR #17 .

Waiting for @ShreyaAnand's 👍 on this!

**Comment by ArpitKotecha** [comment]
> > @vinitshahdeo Please close this issue as it has been resolved in PR #17 .
> 
> Waiting for @ShreyaAnand's 👍 on this!

Okay. Do tell me if any other font has to be used.

**Comment by ArpitKotecha** [comment]
> > > @vinitshahdeo Please close this issue as it has been resolved in PR #17 .
> > 
> > 
> > Waiting for @ShreyaAnand's 👍 on this!
> 
> Okay. Do tell me if any other font has to be used.

**Comment by ShreyaAnand** [comment]
@vinitshahdeo and @ArpitKotecha  it's good.

**Comment by vinitshahdeo** [comment]
@ShreyaAnand I'm closing this issue!
