### ISSUE TITLE
GitHub Live Updates

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#15]
### @ShreyaAnand I'm planning to proceed with this! What's your take on this?

- Create a **`<button ...>View Live Updates</button>`** just below the title content inside `<body>` tag. 

- This button will be linked to **`Live GitHub Commits Notifier`** that I've built. It'll display notifications for the commits made by the participants.

- Until and unless [VinHack](https://vinhack.vinnovateit.com/) starts, we'll make the visiblilty of the button hidden.

```

/* before the hack starts */
#live-updates {
    display : none;
}

/* after the hack starts */
#live-updates {
    display : block;
}

```

@ArpitKotecha  Add the button just below the title and logo of **VinnnovateIT**. Add `javascript` to make the button visible once `current date & time == start time of hack` and as of now, put **#** for  `href`!

**Comment by ArpitKotecha** [comment]
@vinitshahdeo Please close this issue as it has been resolved in  PR #18 .

**Comment by vinitshahdeo** [comment]
> @vinitshahdeo Please close this issue as it has been resolved in PR #18 .

I'm waiting for the @ShreyaAnand's feedback for this `enhancement` in our website. The final product design decision must be approved by President.

**In case, she doesn't like this feature, we may have to revert back the changes made.**

Once done, I'll close.

**Comment by ArpitKotecha** [comment]
> > @vinitshahdeo Please close this issue as it has been resolved in PR #18 .
> 
> I'm waiting for the @ShreyaAnand's feedback for this `enhancement` in our website. The final product design decision must be approved by President.
> 
> **In case, she doesn't like this feature, we may have to revert back the changes made.**
> 
> Once done, I'll close.

Okay.

**Comment by ShreyaAnand** [comment]
Yes this is a good idea. @vinitshahdeo  you can always proceed with your ideas.

**Comment by vinitshahdeo** [comment]
Thanks @ShreyaAnand !

@ArpitKotecha , I am closing this issue.
