### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#19]
@ArpitKotecha 

#### Can you share the report of **Performance Testing**?

I'd suggest you to use chrome's `dev tools` for testing the performance. Test it for different network conditions.

I just want to see **how much loading time has been improved**. If the loading time is not optimum, we'll figure out something to make it better.

Run the test and create a report. Share the link. Mention improvements(if any) too.

**Comment by ArpitKotecha** [comment]
@vinitshahdeo bhaiya, Please merge PR #20  . Then I will create the perfomance report.

**Comment by vinitshahdeo** [comment]
Cool. Merged it!
Now, closing this issue.

**Comment by ArpitKotecha** [comment]
@vinitshahdeo bhaiya, Please find the performance report on the following link:-

- [Mobile Performance Report](https://raw.githubusercontent.com/ArpitKotecha/VinHack-Website/reports/reports/Mobile%20Permonace%20Report.json)
- [Desktop Performance Report](https://raw.githubusercontent.com/ArpitKotecha/VinHack-Website/reports/reports/Desktop%20Permonace%20Report.json)

**Note : To view the reports in interactive form please follow this: [link](https://googlechrome.github.io/lighthouse/viewer/).** (You can save the above given report link in json format and upload it to given the url).

**Comment by ArpitKotecha** [comment]
According to suggestion `lazy loading` is added, `console error bug` is fixed and `rel="noreferrer` is added.
It should result in **Best Pratices score around 💯.** I'll check again after the PR #21 is merged.

Seo suggestions are also implemented in PR #22 . And it should result in SEO score around 💯 .

**Comment by vinitshahdeo** [comment]
**Great work @ArpitKotecha !!**
Checked the scores. It's pretty good!

**Comment by ArpitKotecha** [comment]
@vinitshahdeo bhaiya, Please find the performance report including all the latest changes on the following link:-

- [Mobile Performance Report](https://raw.githubusercontent.com/ArpitKotecha/VinHack-Website/reports/reports/Mobile%20Permonace%20Report.json)
- [Desktop Performance Report](https://raw.githubusercontent.com/ArpitKotecha/VinHack-Website/reports/reports/Desktop%20Permonace%20Report.json)

As you can see in the above given links we got **Best Pratice as well as Seo score 💯**.

**Note: The performance report was create using vit volsbb wifi.**
