### ISSUE TITLE
Fix the HackerEarth Link

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#24]
#### The whole `<div></div>` is not supposed to enclosed inside `<a ..>  </a>`

Fix this @ArpitKotecha !

**Comment by ArpitKotecha** [comment]
Sorry, @vinitshahdeo! Must have forgotten to close the `<a>` tag in hurry. I have merged the PR #25 as it was just the addition of closing `</a>` tag.

**Comment by vinitshahdeo** [comment]
**Chillaxxx** @ArpitKotecha !!
I'm closing this issue.
