### ISSUE TITLE
Grammar Check + SEO test

### ISSUE THREAD

**Issue by vinitshahdeo** [vinnovateit/VinHack-Website#5]
### @ShreyaAnand, please have a sanity check on website content!

- **Spell check**
- Fix **Grammatical errors**, if any!!

Once done, run a **`SEO test`** and make the suggested changes!

**Comment by ArpitKotecha** [comment]
I can also help with this

**Comment by vinitshahdeo** [comment]
> I can also help with this

Sure:)
I am assigning you the same. **Make changes and send PR.**

**Comment by ArpitKotecha** [comment]
@vinitshahdeo Most of the client side SEO changes are made although there are some which needs to be resolved at server/hosting side like  `www redirection Test`, `Domain authority`, etc.,
For more info you can test our site on [SmallSeoTools](https://smallseotools.com).

**Comment by vinitshahdeo** [comment]
We'll see these things later. Currently let's have a measure of **performance** testing. 
> Let's see how much we've improved our website.

@ArpitKotecha
